UPSTREAM: drm/amdgpu: Clean up errors in ih_v6_0.c
Fix the following errors reported by checkpatch:

ERROR: trailing statements should be on next line
ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 46eb29b867e9aba1961dedddb9f2d610cc19214b)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I9de30dbfd09e8834638cc5ebd4ec7a5c7192f2b0