BACKPORT/UPSTREAM: drm/amd/display: fix i386 frame size warning
Addresses the following warning:
drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn30/display_mode_vba_30.c:3596:6: error: stack frame size (2092) exceeds limit (2048) in 'dml30_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
void dml30_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
     ^

UseMinimumDCFCLK() is eating away at
dml30_ModeSupportAndSystemConfigurationFull()'s stack space, so use a
pointer to struct vba_vars_st instead of passing lots of large arrays
as parameters by value.

Change-Id: I2dd86bc4180a112b10ad3a86e0e93406fec2b6d3
Signed-off-by: Hamza Mahfooz <hamza.mahfooz@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit a0f7e7f759cf299ee6f6d8723c596af9a1a86b10)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

Conflicts:
  Extra whitespace removed from stable merge commit: (1c26968caf18
  drm/amd/display: Mark dml30's UseMinimumDCFCLK() as noinline for stack
  usage)

BUG=b:265055111
TEST=Build test

Backported using forklift.py

Change-Id: I4961e241dc898c238fc7a88b39b2ec6e45f406d0