UPSTREAM: drm/radeon: that open brace { should be on the previous line
ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 547e8c5078b6c44fd4f1b0ba7b6e6556ea7a2b42)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I7bb1b4f2ca754b36889ef561fa27d1e6fa756f66