CHROMIUM: config: stoneyridge: Remove Audio configs which is not used
fix config patch to remove compilation error
this function pointer not used in v5.15 base
error: field designator 'delay' does not refer to any field in type 'const struct snd_soc_component_driver'
        .delay          = acp_dma_delay,
         ^
    1 error generated.

BUG=b:233184161
TEST=TESTED on skyrim

Signed-off-by: V sujith kumar Reddy <vsujithkumar.reddy@amd.corp-partner.google.com>
Change-Id: I8df97dedc6afbe0713434771848b2302f14f0faa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3664056
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Commit-Queue: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Tested-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>