FROMGIT: drm/msm/adreno: Do not propagate void return values
With sparse ("make C=2"), lots of

  error: return expression in void function

messages are seen.

Fix this by removing the return statements to propagate void return
values.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Patchwork: https://patchwork.freedesktop.org/patch/492529/
Link: https://lore.kernel.org/r/0083bc7e23753c19902580b902582ae499b44dbf.1657113388.git.geert@linux-m68k.org
Signed-off-by: Rob Clark <robdclark@chromium.org>
(cherry picked from commit d7499634db4f43d3347ae58c5931ad1c795d4cbf
 https://gitlab.freedesktop.org/drm/msm.git msm-next)

BUG=b:232883991, b:187576301
TEST=boot trogdor-arc-r

Change-Id: Ie05d8b74bb6f855f41ad1ba7fed987bf0d43832f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3756562
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Commit-Queue: Rob Clark <robdclark@chromium.org>
Auto-Submit: Rob Clark <robdclark@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
Tested-by: Rob Clark <robdclark@chromium.org>