FIXUP: CHROMIUM: sysrq: Added Chrome OS specific 'x' key
0-day reports:

drivers/tty/sysrq.c: In function 'sysrq_x_cros_signal_process':
drivers/tty/sysrq.c:462:57: error: implicit conversion from 'enum <anonymous>' to 'enum pid_type'

Upstream commit 40b3b0253562 ("signal: Pass pid type into do_send_sig_info")
changed the past parameter from bool to the pid type. Pass PIDTYPE_MAX
to match changes made with that commit.

BUG=None
TEST=Build

Change-Id: I21c164ff5dea37d1577c36c251add42ddbd4494e
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3336098
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Commit-Queue: Dmitry Torokhov <dtor@chromium.org>