FIXUP: CHROMIUM: coiommu: initialize the DMA tracking table
0-day reports:

kernel/dma/coiommu.c:406:21: error: 'MAX_PHYSMEM_BITS' undeclared (first
use in this function)

Coiommu config has a dependency on sparse memory config but
the same has not been written in Kconfigs, which caused the
build to fail on architectures (like alpha) which do not
support sparse memory. Added the required dependencies in
the Kconfig files.

BUG=b:255912146
TEST=Successfully compiled the kernel on Alpha architecture

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I6a235ad745a023353670fb69799e1061641c1b42