UPSTREAM: drm/amd/pm: Clean up errors in smu7.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit e761d50d6833916cc417cade91d1199c4c8c6a5e)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: If0d48af188a93f3294ff37ae11210e2ae579c3aa