UPSTREAM: drm/amdgpu: Clean up errors in vce_v3_0.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 042a70e43a810a814a13c66b9d32e220384ec9bb)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I8c8f88b1edfed13cfe6db4d9861e12e518ea6e46