UPSTREAM: drm/amd/pm: Clean up errors in r600_dpm.h
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 803fe2098ae89d4ce52169f5fd92d4d69626568d)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I51f38325a7b7d39fff6154e3a757a23b715cbf49