UPSTREAM: drm/amd/display: Clean up errors in dce110_hw_sequencer.c
Fix the following errors reported by checkpatch:

ERROR: space required before the open brace '{'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit e822d8392194b53881d60a83ab4d35cfc9e5ec73)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I16d343f7c8cfd18b6a5fe8fd1f072791cd4092a6