FIXUP: FROMLIST: mailbox: Add power_get/power_put API to mbox_chan_ops
Fix compiling error:

>> drivers/mailbox/mailbox.c:382:11: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
     382 |                         return ERR_PTR(ret);
         |                                ^~~~~~~~~~~~

smatch warnings:
drivers/mailbox/mailbox.c:485 mbox_request_channel() error: 'chan' dereferencing possible ERR_PTR()

Bug=None
TEST=make all LLVM=-16
UPSTREAM-TASK=b:386306093

Change-Id: I79de2d304f8bead06a64c6bb0561535f45f94397
Signed-off-by: Helen Koike <koike@igalia.com>
Reported-by: kernel test robot <lkp@intel.com>
Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Closes: https://lore.kernel.org/r/202406151520.TDnOFFbV-lkp@intel.com/
Signed-off-by: Helen Koike <koike@igalia.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/6281543
Reviewed-by: Guilherme Piccoli <gpiccoli@igalia.com>
Commit-Queue: Fei Shao <fshao@chromium.org>
Commit-Queue: Yu-Che Cheng <giver@chromium.org>
Reviewed-by: Fei Shao <fshao@chromium.org>
Reviewed-by: Yu-Che Cheng <giver@chromium.org>
(cherry picked from commit aacf88fa57f457731eb2e436fcc43a87aaad353d)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/6298370
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>