UPSTREAM: drm/amd/display: Clean up errors in dce112_hw_sequencer.c
Fix the following errors reported by checkpatch:

ERROR: space required before the open brace '{'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit a4753953a900f1fb93ca0dd374e0a7b681a280a2)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I022c066035bb49d0240b803803abf38024fc3d3c