UPSTREAM: drm/radeon/si_dpm: open brace '{' following struct go on the same line
ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit be04cf93506bb3f34231e6a638ff0a9eaecc230a)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: If7b9a5f2c05d73d9f240619f0d509e1af6853cdf