CHROMIUM: driver core: Export driver_probe_done
driver_probe_done() is called from dm-verity code, which can be built
as module. Doing so results in the following build failure.

ERROR: "driver_probe_done" [drivers/md/dm-verity.ko] undefined!

BUG=chromium:583462
TEST=Build x86_64:allmodconfig

Change-Id: I1beae02cf83ca0da010dec8028c20c16f05853f9
Fixes: 1326d20b57bc4 ("CHROMIUM: md: dm-verity fixes chromeos needs")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/332289
Reviewed-by: Olof Johansson <olofj@chromium.org>

[rebase44(groeck): Moved patch: export prior to use to avoid build failure]
Signed-off-by: Guenter Roeck <groeck@chromium.org>