UPSTREAM: drm/amd/pm: Clean up errors in smu7_fusion.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line
ERROR: space prohibited before open square bracket '['

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 8377c8bfba624e5010fbe3f4a02bddb3da54eae4)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ic7ed3269fb4717c54bf0625d2672a62307ea06f0