UPSTREAM: drm/amd/pm: Clean up errors in polaris_baco.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 19f6d1dba934e5c6c21afcc2772e4eebb53f28e8)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I69bcd71a0ca09db29ef6f09962d83a67620355ea