UPSTREAM: drm/amd/pm: Clean up errors in fiji_baco.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit ba5d222a6fe925b4cc4615d224159d2d88a4d3dd)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I462355b0f6d96de25ee4e08070c6506f5b3d68c3