FIXUP: CHROMIUM: ARM64: Add alt-syscall support
Fix the following 0-day errors:

> init/init_task.c:71:17: error: use of undeclared identifier
'sys_call_table'
> init/init_task.c:71:17: error: use of undeclared identifier
'compat_sys_call_table'

(https://groups.google.com/g/cros-kernel-buildreports/c/-JcCTqjEcis/m/nEDE_VeOAgAJ)

Note:
Instead of including <asm/syscall.h> which is causing a circular
dependency issue, the fix only copy the necessary extern symbol
declarations.

The circular dependency issue:
In file included from ../include/linux/preempt.h:78:
In file included from ../arch/arm64/include/asm/preempt.h:6:
In file included from ../include/linux/thread_info.h:60:
In file included from ../arch/arm64/include/asm/thread_info.h:31:
In file included from ../arch/arm64/include/asm/syscall.h:9:
In file included from ../include/linux/compat.h:10:
In file included from ../include/linux/time.h:60:
In file included from ../include/linux/time32.h:13:
In file included from ../include/linux/timex.h:67:
In file included from ../arch/arm64/include/asm/timex.h:8:
[...]
error: call to undeclared function 'preempt_disable_notrace'; ISO C99 and later
do not support implicit function declarations [-Wimplicit-function-declaration]

The error message suggests to include <linux/preempt.h> again.

BUG=b:227610040
BUG=b:290153239
BUG=b:291532203
TEST=for arch in amd64-generic arm64-generic arm-generic; do \
       USE=buildtest emerge-"${arch}" chromeos-kernel-6_1; \
     done

Change-Id: Ic419dd389beaf49f018a6a0d081b9a4f95ec5aad
Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4689060
Reviewed-by: Guenter Roeck <groeck@chromium.org>