UPSTREAM: drm/amd/display: Clean up errors in dcn316_clk_mgr.c
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 5cc0ac067494b1b6d324cf9d391730b19e5b431f)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ica5a2d140f265869b45905e91ec47a573b408b00