UPSTREAM: drm/amdgpu: Clean up errors in amdgpu_atombios.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 98268d4033b6bb94cb554d82ca412fc9fd15febc)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Iea10fcadaa84bc9a40d6d4c5446bededc543834b