UPSTREAM: drm/amdgpu: Clean up errors in amdgpu_psp.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line
ERROR: open brace '{' following enum go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 08110c26ce50bba2d2ac79ffb5c3a3d81f5af82a)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ic3524e5d1c0f275f47c9b81b102e9cc10ea6653b