UPSTREAM: drm/amd/display: Clean up errors in dc_stream.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit dfc0cc6828404a9b571d452d6baf1a160aa9b89f)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I4dfa89d223444b43381fe0a8996651f9473a14eb