UPSTREAM: drm/amd/display: Clean up errors in dce110_timing_generator.c
Fix the following errors reported by checkpatch:

ERROR: spaces required around that '=' (ctx:WxV)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit e0b1fe5b31e76dbdbe9f018d5501753038534323)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ic636a20ff1808071add4975f567147f4807973a2