UPSTREAM: drm/amdgpu: Clean up errors in dce_v10_0.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 2b77f199a5a8dc58c1c5404d3abfbb0f45b962c9)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I2e74ddf9291062b0184918105fde6c72a49251f5