UPSTREAM: drm/amd/pm: Clean up errors in amdgpu_smu.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following enum go on the same line
ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 712c6812dcbf69df9752076705ccc762313083e7)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I59801fda8cdc1d9de74546db5ab78f595c53d5a7