UPSTREAM: drm/amd/pm: Clean up errors in vega12_pptable.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line
ERROR: space prohibited before open square bracket '['

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit c066a9e4bfd51f3dc027e10aa819bcf2bff6b049)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I56e3b78bd327469ceaf61cd326791eba10a0b5ff