UPSTREAM: ASoC: rt5682s: use 'static' qualifier
Sparse reports the following warnings:

sound/soc/codecs/rt5682s.c:44:12: error: symbol 'rt5682s_supply_names'
was not declared. Should it be static?

sound/soc/codecs/rt5682s.c:74:26: error: symbol 'rt5682s_reg' was not
declared. Should it be static?

sound/soc/codecs/rt5682s.c:2841:30: error: symbol
'rt5682s_aif1_dai_ops' was not declared. Should it be static?

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20211025185933.144327-3-pierre-louis.bossart@linux.intel.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 49ba5e936e1512d4c7812d433048f8909234fca0
 git://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

BUG=b:210501484
TEST=ODM tests audio function on Chrome device

Signed-off-by: Shuming Fan <shumingf@realtek.com>
Change-Id: I6773746f4f62dbde62e6232ebcb3dee1dfd7eced
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3337643
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Tested-by: Keith Tzeng <keith.tzeng@quanta.corp-partner.google.com>
Commit-Queue: Curtis Malainey <cujomalainey@chromium.org>
(cherry picked from commit beecb8c016be7c3f95231cb6ed0a0ed20cab994a)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3552223
Reviewed-by: Harden Hung <harden.hung@quanta.corp-partner.google.com>
Tested-by: Harden Hung <harden.hung@quanta.corp-partner.google.com>
Reviewed-by: Pin-yen Lin <treapking@chromium.org>
Commit-Queue: Pin-yen Lin <treapking@chromium.org>