FIXUP: CHROMIUM: Bluetooth: surface Intel telemetry events through mgmt
0-day reports:

drivers/bluetooth/btintel.h:318:1: error: expected identifier or
'(' before '{' token

Fix a sytax error.

BUG=b:203035611,b:208922349
TEST=Run an audio a2dp or hfp test and check logs.

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: Id8d7477b7f8f41b9bc45fd7e590f4cf6e7c7e53a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3560778
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Shyh-In Hwang <josephsih@chromium.org>
(cherry picked from commit bfc70ffb61aae06797837930968a65a1a0f69cae)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3829213
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Shyh-In Hwang <josephsih@chromium.org>