FIXUP: CHROMIUM: hardlockup: detect hard lockups without NMIs using secondary cpus
0-day reports:

ld: kernel/watchdog.o: in function `set_sample_period':
kernel/watchdog.c:250: undefined reference to `watchdog_update_hrtimer_threshold'

watchdog_update_hrtimer_threshold is only declared if both
CONFIG_HARDLOCKUP_CHECK_TIMESTAMP and CONFIG_HARDLOCKUP_DETECTOR_PERF
are enabled. Fix dependencies.

BUG=None
TEST=Test builds

Change-Id: Ibe575dfbc7f3eca86c4a96d20f945857fa96cd6f
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3335762
Reviewed-by: Martin Faltesek <mfaltesek@google.com>
Commit-Queue: Martin Faltesek <mfaltesek@google.com>