UPSTREAM: drm/amd/display: Clean up errors in dcn315_smu.c
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line
ERROR: code indent should use tabs where possible

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 06020e1f7ca03960f4b4bc221d64b0fa919d6f31)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Idd9756d9e429f313e1a99272c69c4a48cd304bad