UPSTREAM: drm/radeon: ERROR: "foo * bar" should be "foo *bar"
Fix two occurrences of the checkpatch.pl error:
ERROR: "foo * bar" should be "foo *bar"

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit abbd6cfb1d5a95e8fd07d2fdaa0fe328c2948a52)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I020caaba3cc07cdaf71f4b880ad1a635d7de4419