UPSTREAM: drm/amd/pm: Clean up errors in amdgpu_pm.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line
ERROR: space required before the open parenthesis '('

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit e1b3bcaadfaea728046cf18b6af8efc405eb694d)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I83f535e8f906a601e2eb6e1d4acc45e8ef3f34f0