UPSTREAM: drm/amd/pm: Clean up errors in tonga_baco.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 2ad4f01f19501d2ffc2fe1f7ccccf64d6d5ea93e)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I722e5dc0b3a3fd1c64e09a4e4803c1f92f3077e1