UPSTREAM: drm/amdgpu: Clean up errors in uvd_v3_1.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit c8a1439699923b797d04a396365145de4da18c9c)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ia7c1bd8b3e6e859fcd4c2e1e06dec6a085aab932