UPSTREAM: drivers/amd/pm: Clean up errors in smu8_smumgr.h
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line
ERROR: space prohibited before that ',' (ctx:WxW)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 41c1b492bf013074de4a3ccfb8a62e735043d5b5)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ib18f52bec2fa316a1a2ce4717039982463257c9c