UPSTREAM: drm/amdgpu: Clean up errors in mmhub_v9_4.c
Fix the following errors reported by checkpatch:

ERROR: code indent should use tabs where possible
ERROR: space required before the open parenthesis '('

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit f291f9b9dbee022c30af329c9f70066266ee49ce)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I31bf7597594bdf64c5a175f3df72eadf4639298f