UPSTREAM: drm/amd: Clean up errors in pptable_v1_0.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 08b4dc2fdb35c35708cbf5dab200f1d95fdf1edb)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I1847b58b1d38606841e9ac16fc54c480fd0d7dc4