UPSTREAM: drm/amd/pm: Clean up errors in hardwaremanager.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 6f3d7a6a24516f06e7f025431be1e6dcd0875d5d)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Iad84cbee01da03daa122b2fd1b7c96baab626456