UPSTREAM: drm/amd/pm: Clean up errors in sislands_smc.h
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 5502cf77e8958c9bae949d76e4d977693f7b08d2)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: If60fb3ea16776de7020d9aace07116a333fe68a1