FIXUP: CHROMIUM: MALI: Apply Bifrost r32p0 EAC release (take 2)
0-day reports:

drivers/gpu/arm/bifrost/mali_base_hwconfig_features.h:416:35: error:
	'base_hw_features_tVAx' defined but not used \

and many similar errors. The previous attempt to fix the problem only
addressed static declarations in mali_base_hwconfig_issues.h but missed
the ones in mali_base_hwconfig_features.h. To fix the problem for good,
change the define introduced previously from
_BASE_HWCONFIG_ISSUES_NEED_STATICS to _MALI_BASE_HWCONFIG_NEED_STATICS
and apply it to both include files.

BUG=b:186163221
TEST=Build and install kernel, Kakadu can repeatedly boot to login screen
     Check UI and gfx with https://webglsamples.org/aquarium

Change-Id: I44c72aa828301f82b0f3e9b560f2f100bf8890b8
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3340051
Reviewed-by: Fei Shao <fshao@chromium.org>
Commit-Queue: Fei Shao <fshao@chromium.org>