UPSTREAM: drm/amd/pm: Clean up errors in smu9_driver_if.h
Fix the following errors reported by checkpatch:

ERROR: space prohibited before open square bracket '['

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 29013f607b79fe415d179f9a8575662a1f125fb2)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Icf9eecb624d3991f05795c9335a1a7425c6a2e57