BACKPORT: PCI/PM: Define pci_restore_standard_config() only for CONFIG_PM_SLEEP
pci_restore_standard_config() was defined under CONFIG_PM but called only
by pci_pm_resume() (defined under CONFIG_SUSPEND) and pci_pm_restore()
(defined under CONFIG_HIBERNATE_CALLBACKS).  A configuration with only
CONFIG_PM leads to a warning:

  drivers/pci/pci-driver.c:533:12: error: ‘pci_restore_standard_config’ defined but not used [-Werror=unused-function]

CONFIG_PM_SLEEP depends on CONFIG_SUSPEND and CONFIG_HIBERNATE_CALLBACKS,
so define pci_restore_standard_config() under that instead.

Link: https://lore.kernel.org/r/20220420141135.444820-1-krzysztof.kozlowski@linaro.org
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

(cherry picked from commit 18a94192e20de31e7e495d7c805c8930c42e99ef)

Conflicts:
   drivers/pci/pci-driver.c

BUG=b:227610040
TEST=CQ

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I5b13216597b68cc7ea512efdc00b9ba43ddb8ca0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3782692
Reviewed-by: Guenter Roeck <groeck@chromium.org>