UPSTREAM: drm/amd/display: Clean up errors in dce_clk_mgr.c
Fix the following errors reported by checkpatch:

ERROR: spaces required around that '?' (ctx:VxE)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 0b6c14d496228b33bbad24ea91fe6d9a2df73ab0)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I4a4160ad7c5630a6e93ce5c62f11306629ef5802