UPSTREAM: drm/amdgpu: Clean up errors in mxgpu_vi.c
Fix the following errors reported by checkpatch:

ERROR: spaces required around that '-=' (ctx:WxV)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 599f7c8b85b1c9e747d4c6efd14e111c0a3c0d28)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I348e840e3e4211efc119f5c14308afdfcf832ae1