FIXUP: CHROMIUM: verity: bring over dm-verity-chromeos.c
Since upstream commit 2736e8eeb0cc ("block: use the holder as
indication for exclusive opens"), blkdev_put() accepts a `void *holder`
instead of blk_mode_t.

Fix the following compilation errors:

../drivers/md/dm-verity-chromeos.c: In function ‘chromeos_invalidate_kernel_bio’:
../drivers/md/dm-verity-chromeos.c:197:26: error: passing argument 2 of ‘blkdev_put’ makes pointer from integer without a cast [-Werror=int-conversion]
  197 |         blkdev_put(bdev, dev_mode);
      |                          ^~~~~~~~
      |                          |
      |                          blk_mode_t {aka unsigned int}
In file included from ../drivers/md/dm-verity-chromeos.c:20:
../include/linux/blkdev.h:1481:50: note: expected ‘void *’ but argument is of type ‘blk_mode_t’ {aka ‘unsigned int’}
 1481 | void blkdev_put(struct block_device *bdev, void *holder);
      |                                            ~~~~~~^~~~~~
../drivers/md/dm-verity-chromeos.c:238:34: error: passing argument 2 of ‘blkdev_put’ makes pointer from integer without a cast [-Werror=int-conversion]
  238 |                 blkdev_put(bdev, dev_mode);
      |                                  ^~~~~~~~
      |                                  |
      |                                  blk_mode_t {aka unsigned int}
../include/linux/blkdev.h:1481:50: note: expected ‘void *’ but argument is of type ‘blk_mode_t’ {aka ‘unsigned int’}

BUG=b:295848760
TEST=make allyesconfig drivers/md/dm-verity-chromeos.o

Change-Id: I05eb1babd531e0fe4e66bb63b95160437ad14a7d
Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>