FIXUP: CHROMIUM: alt-syscall: Make required syscalls available for use
0-day complains:

kernel/sys.c:203:5: error: no previous prototype for 'ksys_setpriority' [-Werror=missing-prototypes]
kernel/sys.c:278:5: error: no previous prototype for 'ksys_getpriority' [-Werror=missing-prototypes]
kernel/sys.c:2274:5: error: no previous prototype for 'ksys_prctl' [-Werror=missing-prototypes]
kernel/sys.c:2556:5: error: no previous prototype for 'ksys_getcpu' [-Werror=missing-prototypes]
kernel/time/time.c:354:5: error: no previous prototype for 'ksys_adjtimex_time32' [-Werror=missing-prototypes]
kernel/time/posix-timers.c:1112:5: error: no previous prototype for 'ksys_clock_adjtime' [-Werror=missing-prototypes]
kernel/time/posix-timers.c:1188:5: error: no previous prototype for 'ksys_clock_adjtime32' [-Werror=missing-prototypes]
kernel/events/core.c:11987:5: error: no previous prototype for 'ksys_perf_event_open' [-Werror=missing-prototypes]

Even if the syscalls are only used if ALT_SYSCALL is enabled,
the functions are still exported and need to be declared.

BUG=chromium:885330
TEST=Build and run on any target or in qemu

Change-Id: Ib444a06539e2430d7b045d0ec55dfc7f3b3ecb4e
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3336099
Reviewed-by: Martin Faltesek <mfaltesek@google.com>
Commit-Queue: Martin Faltesek <mfaltesek@google.com>