UPSTREAM: drm/amdgpu: Clean up errors in soc21.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 06d82d87b4fc5ea5ce9f87f2d27a254209545f76)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I0a9d8a9674a6543b19f51a30c037ac92e3ecb5d0