UPSTREAM: drm/radeon: Fix format error
Fix the error(s):

ERROR: space required before the open parenthesis '('

Signed-off-by: Yonggang Wu <wuyonggang001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit c5ee872394971f80fe64a593c2f5716a81712f1c)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I55c49100828a0b7730d5fb74290a1c7004f98b34