BACKPORT: ASoC: Intel: sof_rt5682: shrink platform_id names below 20 characters
Some Chromebooks machine driver aliases exceed 20 characters, which
leads to sparse warnings:

sound/soc/intel/boards/sof_rt5682.c:959:25: error: too long
initializer-string for array of char(no space for nul char)

sound/soc/intel/boards/sof_rt5682.c:989:25: error: too long
initializer-string for array of char(no space for nul char)

sound/soc/intel/boards/sof_rt5682.c:1039:25: error: too long
initializer-string for array of char(no space for nul char)

Fix by using the 'mx' shortcut for Maxim platforms (already used in
platform firmware)

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Reviewed-by: Paul Olaru <paul.olaru@oss.nxp.com>
Reviewed-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
Reviewed-by: Rander Wang <rander.wang@intel.com>
Link: https://lore.kernel.org/r/20210621194057.21711-4-pierre-louis.bossart@linux.intel.com
Signed-off-by: Mark Brown <broonie@kernel.org>

(cherry picked from commit 590cfb082837cc6c0c595adf1711330197c86a58)

Conflicts:
   sound/soc/intel/boards/sof_rt5682.c
   sound/soc/intel/common/soc-acpi-intel-adl-match.c

BUG=b:188623237
TEST=ODM tests audio function on Cret

Signed-off-by: Brent Lu <brent.lu@intel.com>
Change-Id: I85f498822d6e596781580176cc4ace82ecdfb106
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3007478
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Commit-Queue: Curtis Malainey <cujomalainey@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3484344
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Daniel Peng <daniel_peng@pegatron.corp-partner.google.com>
Commit-Queue: YH Lin <yueherngl@chromium.org>