UPSTREAM: drm/amdgpu: Clean up errors in amdgpu_ring.h
Fix the following errors reported by checkpatch:

ERROR: spaces required around that ':' (ctx:VxW)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 1b01c010d7e830db8cec9dee7bb919c9fded43a2)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I9e3b29a870ada4284894397fb9ee95b63423e1f2