UPSTREAM: drm/amd/dc: Clean up errors in hpd_regs.h
Fix the following errors reported by checkpatch:

ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit e8d099e861d12c14c205679001604c673fe8fe63)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ic61daf4194894fb2d3883456c7c4053a7a21e61c