BACKPORT: drm/i915/bios: Validate LFP data table pointers
Make sure the LFP data table pointers sane. Sensible looking
table entries, everything points correctly into the data block,
etc.

Signed-off-by: Ville Syrjälä <ville.syrjala@linux.intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20220405173410.11436-5-ville.syrjala@linux.intel.com
Reviewed-by: Jani Nikula <jani.nikula@intel.com>
(cherry picked from commit 514003e1421e165aa048467af0c6768aab3bb099)

BUG=b:210697438
TEST=Tested on taniks, ensured seamless refresh update

Downstream changes:
-Renamed block_size() to intel_block_size() to avoid the following
 build error:

  /mnt/host/source/src/third_party/kernel/v5.10/drivers/gpu/drm/i915/display/intel_bios.c:136:12:
  error: conflicting types for 'block_size'
  static u32 block_size(const void *bdb, enum bdb_block_id section_id)
             ^
  /mnt/host/source/src/third_party/kernel/v5.10/include/linux/blkdev.h:1659:28:
  note: previous definition is here
  static inline unsigned int block_size(struct block_device *bdev)

Signed-off-by: Sean Paul <seanpaul@chromium.org>
Change-Id: I0b688cf5075c0b7f0857b46154e272ec831daee5