UPSTREAM: ALSA: hda: tas2781: mark const variables as __maybe_unused
An earlier patch changed the DECLARE_TLV_DB_SCALE declaration, but
now there are additional static const variables that cause
the same build warnings:

In file included from sound/pci/hda/tas2781_hda_i2c.c:23:
include/sound/tas2781-tlv.h:23:28: error: 'tas2563_dvc_table' defined but not used [-Werror=unused-const-variable=]
   23 | static const unsigned char tas2563_dvc_table[][4] = {
      |                            ^~~~~~~~~~~~~~~~~
In file included from include/sound/tlv.h:10,
                 from sound/pci/hda/tas2781_hda_i2c.c:22:
include/sound/tas2781-tlv.h:20:35: error: 'tas2563_dvc_tlv' defined but not used [-Werror=unused-const-variable=]
   20 | static const DECLARE_TLV_DB_SCALE(tas2563_dvc_tlv, -12150, 50, 1);
      |                                   ^~~~~~~~~~~~~~~

Mark them all as unused as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20240719095640.3741247-1-arnd@kernel.org
Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit a2d6d8aee4a4f694920bfaf6f6be3690e0f8d302)

BUG=b:195958998
TEST=emerge-geralt sys-kernel/chromeos-kernel-6_1

Change-Id: Icb17280bde8ba8798abe1f17cb3275c704199ce1
Signed-off-by: Rui Zhou <zhourui@huaqin.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5894849
Reviewed-by: Wentao Qin <qinwentao@huaqin.corp-partner.google.com>
Reviewed-by: Fei Shao <fshao@chromium.org>
Reviewed-by: Xinxiong Xu <xuxinxiong@huaqin.corp-partner.google.com>
Reviewed-by: Sean Paul <sean@poorly.run>
(cherry picked from commit 0f50cebcfe0b0547ecf09adec0b71c4b400c88fa)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5918989
Commit-Queue: Fei Shao <fshao@chromium.org>