FIXUP: CHROMIUM: mgmt: support MGMT_OP_GET_VS_OPCODE
0-day error:
>> net/bluetooth/mgmt.c:8776:33: error: 'struct hci_dev' has no
member named 'msft_opcode'

Only access msft_opcode if CONFIG_BT_MSFTEXT is set, otherwise
default to HCI_OP_NOP.

UPSTREAM-TASK=b:254411214
BUG=b:246398494
TEST=emerge

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I432d9619f4c8de8da0d4d686613e2dddd5289111
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4022997
Reviewed-by: Shyh-In Hwang <josephsih@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>