UPSTREAM: drm/amd/pm: Clean up errors in vega20_hwmgr.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following enum go on the same line

Reviewed-by: Evan Quan <evan.quan@amd.com>
Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 8223ef4838c6e7a968d2ae7f598458c22cce5466)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I746752d16abe2a996971119ab2e92546bc0512e4