UPSTREAM: drm/amd/pm: Clean up errors in vega10_powertune.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line
ERROR: space prohibited after that open parenthesis '('

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 223ba2133ee62408a8bf84b9e0444eb6cedd7b3a)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I0c5989e957ce7a30b253c2d5a261693c4f7f1e04