UPSTREAM: drm/amd/pm: Clean up errors in amd_powerplay.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line
ERROR: spaces required around that '||' (ctx:WxO)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 37d67a7adfa99fdee50068021fce29fcddf12d4d)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ie7bac58bb0c7559324691b2a187ecb0fc1d61cb8