UPSTREAM: ASoC: rt5682s: use 'static' qualifier
Sparse reports the following warnings:

sound/soc/codecs/rt5682s.c:44:12: error: symbol 'rt5682s_supply_names'
was not declared. Should it be static?

sound/soc/codecs/rt5682s.c:74:26: error: symbol 'rt5682s_reg' was not
declared. Should it be static?

sound/soc/codecs/rt5682s.c:2841:30: error: symbol
'rt5682s_aif1_dai_ops' was not declared. Should it be static?

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
(cherry picked from commit 49ba5e936e1512d4c7812d433048f8909234fca0)

BUG=b:198716740
TEST=ODM tests audio function on Chrome device

Signed-off-by: Oder Chiou <oder_chiou@realtek.com>
Change-Id: I042f196483bb24e0586e920f9036558e4c0583fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3261413
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Tested-by: Asher Huang <asher_huang@pegatron.corp-partner.google.com>
Commit-Queue: Curtis Malainey <cujomalainey@chromium.org>
(cherry picked from commit 518f9bb72e22a513294f174112e9e344685d04d7)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3322504
Reviewed-by: Asher Huang <asher_huang@pegatron.corp-partner.google.com>
Reviewed-by: Shou-Chieh Hsu <shouchieh@chromium.org>
Commit-Queue: Shou-Chieh Hsu <shouchieh@chromium.org>