UPSTREAM: drm/amdgpu: Clean up errors in cik_ih.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 9c7f00f7d13b192408db083a83b15cc03a4ac635)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I7f1fa68ee2f561f0a4ae08e57af77209e32c4054