UPSTREAM: drm/amd/display: Clean up errors in ddc_regs.h
Fix the following errors reported by checkpatch:

ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 784c1cc51391fbde51d293ad6137ab4faeff8ec1)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I4a3f918a1f9379d604d4521c7b632020fe4b3b66