FIXUP: NOUPSTREAM: ANDROID: usb: gadget: f_audio_source: New gadget driver for audio output
0-day reports:

ERROR: modpost: "create_function_device"
	[drivers/usb/gadget/function/usb_f_audio_source.ko] undefined!

create_function_device is only available if USB_CONFIGFS_UEVENT
is enabled. Add the missing dependency.

BUG=b:204914950
TEST=Build with USB_CONFIGFS_UEVENT=n

Change-Id: I3dead65cca41f410b010b71aa3f2528e5e5c30e1
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3315716
Commit-Queue: Martin Faltesek <mfaltesek@google.com>
Reviewed-by: Martin Faltesek <mfaltesek@google.com>